### ISSUE TITLE
请教下真机不报错但不显示，模拟器中可以显示是什么问题

### ISSUE THREAD

**Issue by JJH0901** [landn172/lottie-miniapp#141] opened 2020-01-07 08:01 UTC
**bug描述**
真机（安卓、ios）不报错但不显示，模拟器中可以显示
查看canvasContext在真机和模拟器中的值，真机中没有_context属性，如下图：
<img width="818" alt="WX20200107-160238@2x" src="https://user-images.githubusercontent.com/19657983/71878725-5410c880-3167-11ea-8cf5-d4c781f8d4ab.png">
<img width="866" alt="WX20200107-160259@2x" src="https://user-images.githubusercontent.com/19657983/71878758-67239880-3167-11ea-8951-8c1f0555c94e.png">

**Comment by landn172** [comment] 2020-01-07 09:16
@JJH0901 把对应的json文件发出来

**Comment by landn172** [comment] 2020-01-07 09:28
Duplicate of #69

**Comment by JJH0901** [comment] 2020-01-08 02:05
@landn172 看到您上面发的链接问题了，去掉域名校验也可以显示，我这段json不包含图片链接
{
	"v": "5.5.10",
	"fr": 24,
	"ip": 0,
	"op": 24,
	"w": 100,
	"h": 100,
	"nm": "blue/LANDING",
	"ddd": 0,
	"assets": [],
	"layers": [{
		"ddd": 0,
		"ind": 1,
		"ty": 4,
		"nm": "blue/LANDING Outlines",
		"sr": 1,
		"ks": {
			"o": {
				"a": 0,
				"k": 100,
				"ix": 11
			},
			"r": {
				"a": 0,
				"k": 0,
				"ix": 10
			},
			"p": {
				"a": 1,
				"k": [{
					"i": {
						"x": 0.833,
						"y": 0.833
					},
					"o": {
						"x": 0.167,
						"y": 0.167
					},
					"t": 0,
					"s": [45, 50, 0],
					"to": [0, 0, 0],
					"ti": [0, 0, 0]
				}, {
					"i": {
						"x": 0.833,
						"y": 0.833
					},
					"o": {
						"x": 0.167,
						"y": 0.167
					},
					"t": 11,
					"s": [80, 50, 0],
					"to": [0, 0, 0],
					"ti": [0, 0, 0]
				}, {
					"t": 24,
					"s": [45, 50, 0]
				}],
				"ix": 2
			},
			"a": {
				"a": 0,
				"k": [100, 100, 0],
				"ix": 1
			},
			"s": {
				"a": 0,
				"k": [50, 50, 100],
				"ix": 6
			}
		},
		"ao": 0,
		"shapes": [{
			"ty": "gr",
			"it": [{
				"ind": 0,
				"ty": "sh",
				"ix": 1,
				"ks": {
					"a": 0,
					"k": {
						"i": [
							[0, -7.732],
							[7.732, 0],
							[0, 7.732],
							[-7.732, 0]
						],
						"o": [
							[0, 7.732],
							[-7.732, 0],
							[0, -7.732],
							[7.732, 0]
						],
						"v": [
							[14, 0],
							[0, 14],
							[-14, 0],
							[0, -14]
						],
						"c": true
					},
					"ix": 2
				},
				"nm": "Path 1",
				"mn": "ADBE Vector Shape - Group",
				"hd": false
			}, {
				"ty": "fl",
				"c": {
					"a": 0,
					"k": [0.141000007181, 0.40800000359, 0.957000014361, 1],
					"ix": 4
				},
				"o": {
					"a": 0,
					"k": 100,
					"ix": 5
				},
				"r": 1,
				"bm": 0,
				"nm": "Fill 1",
				"mn": "ADBE Vector Graphic - Fill",
				"hd": false
			}, {
				"ty": "tr",
				"p": {
					"a": 0,
					"k": [76, 100],
					"ix": 2
				},
				"a": {
					"a": 0,
					"k": [0, 0],
					"ix": 1
				},
				"s": {
					"a": 0,
					"k": [100, 100],
					"ix": 3
				},
				"r": {
					"a": 0,
					"k": 0,
					"ix": 6
				},
				"o": {
					"a": 0,
					"k": 100,
					"ix": 7
				},
				"sk": {
					"a": 0,
					"k": 0,
					"ix": 4
				},
				"sa": {
					"a": 0,
					"k": 0,
					"ix": 5
				},
				"nm": "Transform"
			}],
			"nm": "Group 1",
			"np": 2,
			"cix": 2,
			"bm": 0,
			"ix": 1,
			"mn": "ADBE Vector Group",
			"hd": false
		}],
		"ip": 0,
		"op": 24,
		"st": 0,
		"bm": 0
	}, {
		"ddd": 0,
		"ind": 3,
		"ty": 4,
		"nm": "red/LANDING Outlines",
		"sr": 1,
		"ks": {
			"o": {
				"a": 0,
				"k": 100,
				"ix": 11
			},
			"r": {
				"a": 0,
				"k": 0,
				"ix": 10
			},
			"p": {
				"a": 1,
				"k": [{
					"i": {
						"x": 0.833,
						"y": 0.833
					},
					"o": {
						"x": 0.167,
						"y": 0.167
					},
					"t": 0,
					"s": [45, 50, 0],
					"to": [0, 0, 0],
					"ti": [0, 0, 0]
				}, {
					"i": {
						"x": 0.833,
						"y": 0.833
					},
					"o": {
						"x": 0.167,
						"y": 0.167
					},
					"t": 11,
					"s": [10, 50, 0],
					"to": [0, 0, 0],
					"ti": [0, 0, 0]
				}, {
					"t": 24,
					"s": [45, 50, 0]
				}],
				"ix": 2
			},
			"a": {
				"a": 0,
				"k": [80, 100, 0],
				"ix": 1
			},
			"s": {
				"a": 0,
				"k": [50, 50, 100],
				"ix": 6
			}
		},
		"ao": 0,
		"shapes": [{
			"ty": "gr",
			"it": [{
				"ind": 0,
				"ty": "sh",
				"ix": 1,
				"ks": {
					"a": 0,
					"k": {
						"i": [
							[0, -7.732],
							[7.732, 0],
							[0, 7.732],
							[-7.732, 0]
						],
						"o": [
							[0, 7.732],
							[-7.732, 0],
							[0, -7.732],
							[7.732, 0]
						],
						"v": [
							[14, 0],
							[0, 14],
							[-14, 0],
							[0, -14]
						],
						"c": true
					},
					"ix": 2
				},
				"nm": "Path 1",
				"mn": "ADBE Vector Shape - Group",
				"hd": false
			}, {
				"ty": "fl",
				"c": {
					"a": 0,
					"k": [0.961000031116, 0.258999992819, 0.211999990426, 1],
					"ix": 4
				},
				"o": {
					"a": 0,
					"k": 100,
					"ix": 5
				},
				"r": 1,
				"bm": 0,
				"nm": "Fill 1",
				"mn": "ADBE Vector Graphic - Fill",
				"hd": false
			}, {
				"ty": "tr",
				"p": {
					"a": 0,
					"k": [124, 100],
					"ix": 2
				},
				"a": {
					"a": 0,
					"k": [0, 0],
					"ix": 1
				},
				"s": {
					"a": 0,
					"k": [100, 100],
					"ix": 3
				},
				"r": {
					"a": 0,
					"k": 0,
					"ix": 6
				},
				"o": {
					"a": 0,
					"k": 100,
					"ix": 7
				},
				"sk": {
					"a": 0,
					"k": 0,
					"ix": 4
				},
				"sa": {
					"a": 0,
					"k": 0,
					"ix": 5
				},
				"nm": "Transform"
			}],
			"nm": "Group 1",
			"np": 2,
			"cix": 2,
			"bm": 0,
			"ix": 1,
			"mn": "ADBE Vector Group",
			"hd": false
		}],
		"ip": 0,
		"op": 24,
		"st": 0,
		"bm": 0
	}],
	"markers": []
}

**Comment by landn172** [comment] 2020-01-08 02:51
https://github.com/landn172/lottie-miniapp/tree/issues-141
@JJH0901 跑了下没问题，安卓、IOS都正常。
![image](https://user-images.githubusercontent.com/4362412/71946451-dd2a0d00-3204-11ea-8f1a-0308cdc3f765.png)

**Closed by landn172** 2020-01-08 02:51 UTC

**Comment by JJH0901** [comment] 2020-01-08 03:25
好的，谢谢您，我再看看是不是我的程序有问题
